### ISSUE TITLE
Does not work with WINE

### ISSUE THREAD

**Issue by Sarvasv-0** [openmultiplayer/launcher#10]
I know this would not reach the top of the priority list as very less users use wine, I will still try to explain the difficulty
---
The version of wine: `wine-8.0.2` from winehq
Distro: Fedora Workstation 38
What caused the error: I tried to start `omp-launcher.exe` from my downloads folder
Command used: `wine ~/Downloads/omp-launcher.exe` (default wineprefix)
logs: 
![image](https://github.com/openmultiplayer/launcher/assets/81177923/c91ea108-bbf0-47cc-88d5-67f3d02fe344)

PS: If it is not possible to fix the error with the portable version just let me know, I can also try on my windows machine

**Comment by AmyrAhmady** [comment]
Have you installed webview2 through Wine? as it is instructed in readme, it's a requirement.

**Comment by AmyrAhmady** [comment]
Actually, instead of manually installing WebView2, you can run this through Wine and it should install required dependencies for you

https://github.com/openmultiplayer/launcher/releases/download/v0.0.1/omp-launcher_0.0.1_x64-setup.exe

Hit me up with the updates when you do it.

**Comment by SoxxZ** [comment]
not working here too. tried installing webview manually, but the exe doesnt even open.
![image](https://github.com/openmultiplayer/launcher/assets/14855972/e88909ac-8c5b-4969-a733-3a0047167d37)

**Comment by Heus-Sueh** [comment]
> not working here too. tried installing webview manually, but the exe doesnt even open. ![image](https://private-user-images.githubusercontent.com/14855972/282318819-e88909ac-8c5b-4969-a733-3a0047167d37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNTExMjQsIm5iZiI6MTcwMzM1MDgyNCwicGF0aCI6Ii8xNDg1NTk3Mi8yODIzMTg4MTktZTg4OTA5YWMtOGM1Yi00OTY5LWE3MzMtM2EwMDQ3MTY3ZDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDE3MDAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNTVhZjFhZjM1M2I1NGM5M2U2N2NjYjkzYjRiNWQ1M2MwMjc0MjA1OTA0NjIzYjI1OWUyMzNlZWNmZmQ4YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B-VdXhNpHh8WuCtN1aCU6iNdSBDWkJuNYeYmdH-MmDc)

I can confirm that the same happens to me

**Comment by Heus-Sueh** [comment]
You may need to create a bug report on the [WineHQ website](https://bugs.winehq.org/)

**Comment by Heus-Sueh** [comment]
to keep updated on any changes to edge webview:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3127

**Comment by MarioStojcevski** [comment]
im not sure whats happening here im a newbie with wine, but it seems it has an issue. i will post this just a reference to what im seeing, i dont think the full terminal output is needed. if someone know how to get support for this it would be awesome

![image](https://github.com/openmultiplayer/launcher/assets/61598148/46c08537-a79a-4976-86e1-de5a5c86b0fb)

**Comment by Sarvasv-0** [comment]
![image](https://github.com/openmultiplayer/launcher/assets/81177923/8a4369a3-5f72-41fa-b48c-9d64338075e1)
I tried this again with v1 of the installer and apparently it is stuck at the installation, apparently the `/silent` flag is making it worse

**Comment by AmyrAhmady** [comment]
I think you guys are ignoring one of the comments so I post it myself again
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3127

The issue is from WebView2, not open.mp launcher, it's not compatible with WINE. The proper way of doing it is releasing a linux version of it that runs gtasa and samp using WINE. Closing this issue because there's no point

**Comment by blacklightpy** [comment]
In case anyone's looking for it, it does not work on Proton (Proton Experimental) either.

**Comment by dzmtrzz** [comment]
Reviving this thread, because i GOT IT RUNNING GUYS!!!
(not the launcher, but the client, which is good enough for me)

> It works!! It launches itself just fine!! All you need to do, is put the omp-client.dll file in the folder AppData\Local\com.open.mp\omp\ (the dll file is at https://assets.open.mp/omp-client.dll)
> You have to install allfonts in winetricks, or else the game crashes when you pause
> Also, for me it was kind of wonky with "prefer system libraries" in lutris.

For the record, you do not get the gui, you need to connect to servers with the command line, or a batch script that runs the command.

**Comment by blacklightpy** [comment]
I found this [guide](https://dev.to/lionthehoon/fixing-webview2-issues-in-linux-bottles-how-i-got-it-working-1ab6) to make WebView2 work on Wine, and people are reporting that it works. I haven't tried it myself as I'm not using my laptop for a while.

**Comment by itsneufox** [comment]
> I found this [guide](https://dev.to/lionthehoon/fixing-webview2-issues-in-linux-bottles-how-i-got-it-working-1ab6) to make WebView2 work on Wine, and people are reporting that it works. I haven't tried it myself as I'm not using my laptop for a while.

I am going to check it out later and test, if it works maybe it's worth that i update the wiki.

**Comment by Fanorisky** [comment]
> I found this [guide](https://dev.to/lionthehoon/fixing-webview2-issues-in-linux-bottles-how-i-got-it-working-1ab6) to make WebView2 work on Wine, and people are reporting that it works. I haven't tried it myself as I'm not using my laptop for a while.

does it works with lutris tho? i'll try
