### ISSUE TITLE
[FEATURE REQUEST] Recent nicknames

### ISSUE THREAD

**Issue by wiger3** [openmultiplayer/launcher#110]
Hi, I think it would be nice to be able to select a nickname from a list of recently used ones when connecting to a server.
This would help people that have different nicknames on different servers, or people that play on Role Play servers on multiple accounts.

**Comment by AmyrAhmady** [comment]
The nickname input when you double click a server is "per server nickname", once modified and changed (compared to global nickname), it is saved and lets you play with that nickname as long as you don't removed it (if you remove it it becomes global nickname)

Recently used names is just too much in my opinion to add, makes things even more complex on the code side and UI wise, it's not worth it to be fair. but as per server nicknames, it's already in and working
