### ISSUE TITLE
Can't open omp-launcher by windows tab

### ISSUE THREAD

**Issue by pushline** [openmultiplayer/launcher#113]
I can't open the exe by the windows tab. Idk if it has to be a registered exe or something, and idk if its supposed to happen or not.
Video trying to open it:
https://www.youtube.com/watch?v=2nqbS4Djl9A

**Comment by VictorMacielGhost** [comment]
Works on my machine 
https://youtu.be/PREdjSQwXA8

**Comment by FreddieCrew** [comment]
Works fine for me. I'm using version [1.0.0](https://github.com/openmultiplayer/launcher/releases/tag/v1.0.0).

https://www.youtube.com/watch?v=YDyzrC2mkqc
