### ISSUE TITLE
Open mp launcher - server password issue

### ISSUE THREAD

**Issue by 0xDizzle** [openmultiplayer/launcher#116]
When players try to connect to a server that was previously passworded (only if they actually connected to it using a password before) it will keep saying "incorrect password" for them or they'll be stuck in a "connecting to..." loop, even though the server password was removed.

To reproduce the bug:
set a server password in config.json
open the server
connect to it using the password set earlier
/q and close the server
remove the password from config.json
open the server and try to connect
it will say incorrect password or will keep trying to connect to no avail

**Comment by Sreyas-Sreelal** [comment]
Probably modifying following condition before prompting for password would be enough.

https://github.com/openmultiplayer/launcher/blob/067701a0726a389cdf5854017b669e351010ef5c/src/containers/JoinServerPrompt/index.tsx#L127

Like `(server?.hasPassword || server?.password.length)`. Simply prompting if password is found in stored data, with stored password in input. 

Another method would be simply removing the stored password if `hasPassword` is false.

**Comment by AmyrAhmady** [comment]
Fixed with https://github.com/openmultiplayer/launcher/commit/a0976cfd9a0e1a61c812906e201ddbfe73f08ac4
