### ISSUE TITLE
Add a CLI to launch the game

### ISSUE THREAD

**Issue by Vladik01-11** [openmultiplayer/launcher#120]
It would be great if you did that if, when launching the launcher with certain arguments, such as --IP and --PORT, as well as additional arguments, if specified by the user, --PASSWORD, --NAME, --DIRECTORY, the game was immediately launched, it's just very convenient for me personally and I think some people like it would be nice for me to see it right in this launcher.

An excellent example is this open source repository, it literally does everything that I wrote above, but it is not very convenient to use 2 third-party programs at once for, in fact, the same thing.
https://github.com/RinatNamazov/SampConsoleLauncher

**Comment by AmyrAhmady** [comment]
available in next release
```
❯ .\omp-launcher.exe --help
open.mp launcher

Usage: omp-launcher.exe [OPTIONS]

Options:
      --help
  -h, --host <HOST>          Server IP [default: ]
  -p, --port <PORT>          Server port [default: 0]
  -n, --name <NAME>          Nickname [default: ]
  -g, --gamepath <GAMEPATH>  Game path [default: ]
  -V, --version              Print version
```
