### ISSUE TITLE
problem with the open.MP Launcher 

### ISSUE THREAD

**Issue by bobili1** [openmultiplayer/launcher#134]
For GTA San Andreas I have a version for Hooligans 😋 this simple SA-MP works normally for me 

But when I want to enter SA-MP via open.MP, I need to try it 1000000 times to get even 0.1% to start SA-MP, and mostly it starts me with regular GTA SAN ANDREAS 

And I am not able to install ie. I download the original full version of GTA SA due to the lack of any memory 

![Uploading IMG_20240328_005353.jpg…]()

**Comment by midosvt** [comment]
You probably have the wrong version of San Andreas. So maybe download the one we have in our Discord? Or it looks like you can't?

**Comment by AmyrAhmady** [comment]
Closing this due to no replies
