### ISSUE TITLE
Refresh button

### ISSUE THREAD

**Issue by BaxAndrei** [openmultiplayer/launcher#145]
Hello!

Can you please add refresh button too? We are so used to this feauture.

For example if server goes down, I cant refresh it to see new status so I need to restart open.mp
![image](https://github.com/openmultiplayer/launcher/assets/12484505/d0022e36-9844-4654-b63f-6559fc652292)

**Comment by AmyrAhmady** [comment]
You don't need to refresh it
If it goes down and you still have the server selected, it pings when your server comes back
just having it selected basically keeps refreshing it

**Comment by BaxAndrei** [comment]
Thank you @AmyrAhmady . I see now.

But is there any chance to make it says 0/0 if server gets down until it gets up again? RN if last ping was 100/1000 but server get down, it will stay 100/1000 until server restarts.

Thank you!
