### ISSUE TITLE
PERGUNTANDO OQ ELES REALMENTE ESTÃO PENSANDO EM FAZER, CRIAR UM SAMP NOVO?

### ISSUE THREAD

**Issue by zMcloviin** [openmultiplayer/launcher#175]
OQ VCS PENSAM EM FAZER DEPOIS DO ACONTECIDO?
PENSAM EM CRIAR UM SAMP NOVO?
Q HORAS MAIS OU MENOS IRÃO ACABAR?
A COMUNIDADE ESTA ANSIOSA!!

**Comment by AmyrAhmady** [comment]
English only

**Comment by Southclaws** [comment]
this is pure poetry.
