### ISSUE TITLE
Mouse DPI setting corruption

### ISSUE THREAD

**Issue by fieL582** [openmultiplayer/launcher#177]
Hello, when I connect to a server using omp-launcher.exe, the portable version of `Open.mp` (without installation), the DPI setting of my mouse suddenly increases and this problem persists even when I exit the game. I fix this problem by manually adjusting the mouse DPI.
![Ekran görüntüsü 2024-07-27 024718](https://github.com/user-attachments/assets/f8ae67b2-5c7d-4562-b621-3d7d414d2172)

**Comment by AmyrAhmady** [comment]
@fieL582
