### ISSUE TITLE
 Incorrect Server Password (even though the server doesn't have a password)

### ISSUE THREAD

**Issue by Kymm05** [openmultiplayer/launcher#187]
![image](https://github.com/user-attachments/assets/32b96e1d-4796-4825-a2be-23eb1a3fac8c)
![sa-mp-053](https://github.com/user-attachments/assets/578e941c-0b01-4512-a87a-33d55fc23b91)

**Comment by AmyrAhmady** [comment]
I'm not able to reproduce this with latest nightly, if you can test it I'd be appreciated
