### ISSUE TITLE
Launcher bug

### ISSUE THREAD

**Issue by devmalone74** [openmultiplayer/launcher#201]
When you connect a local server and access it through the open.mp launcher, the server needs to have a password so that you can access the server.

This is not very important, but it is good to solve the problem.

**Comment by karthigenius** [comment]
> When you connect a local server and access it through the open.mp launcher, the server needs to have a password so that you can access the server.
> 
> This is not very important, but it is good to solve the problem.

Could you attach any videos.

cuz, its working good in Both OMP Server and SAMP Server in Launcher while Connecting, The issue you mentioned doesn't occurred...

**Comment by AmyrAhmady** [comment]
no replies yet
