### ISSUE TITLE
Launcher version abnormality

### ISSUE THREAD

**Issue by Bt6K** [openmultiplayer/launcher#221]
On my desktop computer running **Windows 11**, when I launch the game, I get the following: https://i.imgur.com/gZ2x90R.png

Notice how it mentions "open.mp modification" in the chat.

If I hit ESC, it correctly shows v0.0.1 in the bottom right hand corner.

**All is fine here, no issues.**

**However**, if I install open.mp using the exact same procedure on my **Windows 10** laptop, there's no mention of "open.mp modification" in the chat, and likewise, there is no v0.0.1 in the bottom right hand corner when hitting ESC.

In both instances, I grabbed the latest open.mp launcher from [here](https://github.com/openmultiplayer/launcher/releases/download/v1.4.0/omp-launcher-setup.exe) and I used the SA-MP client from [here](https://gta-multiplayer.cz/downloads/sa-mp-0.3.7-R5-2-MP-install.exe). I also used the same version of GTA SA from [here](https://amii.ir/files/hlm-gtasa.iso).

So, everything is identical - except that one device runs Windows 10, and the other runs Windows 11

Any thoughts as to why this might be?

**Comment by AmyrAhmady** [comment]
because it's not loaded, probably due to missing vc++ redistributables
