### ISSUE TITLE
Suggestion: Ability to Detect if a Player is Using the open.mp Launcher

### ISSUE THREAD

**Issue by thelante** [openmultiplayer/launcher#235]
It would be great to have a feature that detects whether a player is using the open.mp launcher. This would allow server owners to reward players for choosing the open.mp launcher, encouraging more players to adopt it. By offering incentives, it could help raise awareness of open.mp and promote its usage within the community.

**Comment by myudev** [comment]
You could detect it already with SendClientCheck if u really wanted btw

**Comment by AmyrAhmady** [comment]
fixed in next release
