### ISSUE TITLE
Feature: OMP Launcher Installer has an ability to download Clean GTA Lite and Full Version.

### ISSUE THREAD

**Issue by eksqtr** [openmultiplayer/launcher#255]
It would be great and hassle-free for new players to have this feature available in the launcher, potentially bringing in a new community. My idea is to add a button in the settings that allows users to install or reinstall either the Lite version of GTA
(without audio) or the full version (with audio).

Additionally, for first-time launcher installations, the launcher could prompt the user to indicate whether they already have GTA
installed. If not, it could suggest downloading and installing the game or allow them to skip this step.

**Pros:**
- Hassle-Free for New Players: Makes it easier for newcomers to join the GTA
multiplayer community without complications.
- Saves Time: Reduces the need for players to ask in Discord where or how to download GTA
- Safe, Clean Downloads: Ensures that game files are downloaded directly from trusted sources hosted by open.mp.

**Cons:**
- Bandwidth Costs: This could increase the bandwidth usage due to the game files being hosted and downloaded.

**Comment by Vince0789** [comment]
Won't be done. Copyright. There might be a case for this if the game was abandonware, but it is still being sold in the Rockstar store right now. Albeit a crappy version that doesn't work with this mod.

**Comment by AmyrAhmady** [comment]
Vince said it perfectly, closing
