### ISSUE TITLE
BUG: "Enable Discord status" setting not working correctly

### ISSUE THREAD

**Issue by Corrado346** [openmultiplayer/launcher#256]
![image](https://github.com/user-attachments/assets/59a2a690-0e64-4abc-8774-e66c98497879)

Worst censoring job aside I can not turn off Discord presence.
I have tried reinstalling open.mp but it did not work.
My goal is turning OFF Discord presence but I can't do it no matter what.

**Comment by eksqtr** [comment]
I confirmed this same with my case. In Windows 11 and running the omp launcher as Administrator. Toggling off the Discord presence still on

**Comment by itsneufox** [comment]
![image](https://github.com/user-attachments/assets/e33e9d51-8b54-45de-9bc4-e30c14195818)
Can confirm on my sidetoo, even closed it and opened again to check.

**Comment by Corrado346** [comment]
> Are you sure you're not running two instances of open.mp launcher at once?

I am sure.

> I can confirm the same on my end. I tried closing and reopening it to test, and the behavior is inconsistent—sometimes it doesn’t display, while other times it keeps displaying and won’t stop displaying,
> 
> removed image because at the moment of the print it stopped displaying...
> 
> https://www.youtube.com/watch?v=tLjUF2gHRkc
> 
> in this video it stops displaying permanently until restart

This issue seems to be a completely different one, when I toggle the option on and off nothing is happening (the discord status is displayed no matter if the option is turned on or off) while your issue happens after a few toggles

**Comment by AmyrAhmady** [comment]
fixed next release
