### ISSUE TITLE
Ping as 9999

### ISSUE THREAD

**Issue by NexiusTailer** [openmultiplayer/launcher#28]
There is a suggestion about "no ping" displaying. Recent changes made it show as "9999" for inactive servers, like this one:
![image](https://github.com/openmultiplayer/launcher/assets/13169094/d8d7cad6-2985-45b3-af63-ae55acbeac5b)

but looks pretty weird isn't it?

Maybe a samp launcher approach will be better: just show "-" (minus) if there is no information about ping at the moment.

**Comment by AmyrAhmady** [comment]
it's showing as `-` now.
