### ISSUE TITLE
Add some pictures to readme.md

### ISSUE THREAD

**Issue by coool9** [openmultiplayer/launcher#3]

**Comment by Mortyyka** [comment]
like what and why

**Comment by pushline** [comment]
peak issue

**Comment by NexiusTailer** [comment]
> like what and why

its window, to see how it looks like

**Comment by Mortyyka** [comment]
> > like what and why
> 
> its window, to see how it looks like

Just download it and see for yourself, the design shouldn't be what makes you install it anyway

**Comment by NexiusTailer** [comment]
> > > like what and why
> > 
> > 
> > its window, to see how it looks like
> 
> Just download it and see for yourself, the design shouldn't be what makes you install it anyway

It is literally what makes me install it or not from the first sight

**Comment by Mortyyka** [comment]
> > > > like what and why
> > > 
> > > 
> > > its window, to see how it looks like
> > 
> > 
> > Just download it and see for yourself, the design shouldn't be what makes you install it anyway
> 
> It is literally what makes me install it or not from the first sight

>Gogie creates something revolutionary

>User looks at UI
>Looks bas
>User wont use it because the UI is like html without css
>User misses out on good shit just because he wouldn't use the UI due to the lack of design, not functionality

**Comment by NexiusTailer** [comment]
> > Gogie creates something revolutionary
> 
> > User looks at UI
> > Looks bas
> > User wont use it because the UI is like html without css
> > User misses out on good shit just because he wouldn't use the UI due to the lack of design, not functionality

So what's the problem to let people know about it before they download it and do exactly the same you described if it were true.
This way you just:
a) save their time if they're not interested
b) make a better promo if it looks really good and they are interested (so they can share this to other friends without even downloading first)

**Comment by Mortyyka** [comment]
> > > Gogie creates something revolutionary
> > 
> > 
> > > User looks at UI
> > > Looks bas
> > > User wont use it because the UI is like html without css
> > > User misses out on good shit just because he wouldn't use the UI due to the lack of design, not functionality
> 
> So what's the problem to let people know about it before they download it and do exactly the same you described if it were true. This way you just: a) save their time if they're not interested b) make a better promo if it looks really good and they are interested (so they can share this to other friends without even downloading first)

Okay, so i am not interested in the useful feautres that other applications may not have because the UI isn't the best looking. 

b, make a promo: hey guys here is this nice crypto site looks really good you must use this (has tons of flaws, actually wants to steal your data, but its okay the design is good)

**Comment by coool9** [comment]
I am surprised someone is even arguing against this. 
Add the UI pics and add the other useful features too to the readme. Hiding pics so people will install the app is evil.

**Comment by Mortyyka** [comment]
> I am surprised someone is even arguing against this. Add the UI pics and add the other useful features too to the readme. Hiding pics so people will install the app is evil.

No, it isn't this way you're not bloating the readme. Maybe refer to a new md in the readme with the pics, dont directly bloat the readme.

**Comment by AmyrAhmady** [comment]
This is has nothing to with making it bloated, adding some pictures won't hurt anyone
I'll get to it when I do some other stuff with higher priority.
