### ISSUE TITLE
Add more options to dropdown menu

### ISSUE THREAD

**Issue by r4sheed** [openmultiplayer/launcher#35]
Add missing options from the right click dropdown menu, especially the 'Connect' button.
![kép](https://github.com/openmultiplayer/launcher/assets/25135303/dfe788cd-cd52-440f-be77-1ece1df3c406)

**Comment by AmyrAhmady** [comment]
Added connect button, the rest are useless imo, refreshing server data can be done when you select it, add & delete are combined, copy is available, no need for server props
