### ISSUE TITLE
Servers added to Favorites are not queried

### ISSUE THREAD

**Issue by edgyaf** [openmultiplayer/launcher#41]
Servers, when added to the Favorites list, display with a default name indicating that there is no information about the server. After adding a server, the launcher should send a one-time query to the server to acquire basic information, just as it happens in SA-MP launcher, without having to click separately on the server to send the query.

**Comment by AmyrAhmady** [comment]
Fixed in https://github.com/openmultiplayer/launcher/commit/a54162986405d0b3e973eac10235826ccdfd6591
