### ISSUE TITLE
Launcher start singleplayer instead of multiplayer

### ISSUE THREAD

**Issue by Sef69** [openmultiplayer/launcher#47]
So, sometimes launcher start singleplayer instead of multiplayer. How ? I'm not sure 100%, but I'm still trying to recognize, this is some thing that I found and maybe it's that. When I shut down/restart my computer, and after that when I first time start the launcher and try to connect to server it puts me in a singleplayer mode, when I leave singleplayer and try again to connect to server, then it puts me in multiplayer mode, so only first time when I try to connect to server it puts me in a singeplayer, after that normally in multiplayer.

**Comment by AmyrAhmady** [comment]
Duplicate #9
