### ISSUE TITLE
How to contribute a translation?

### ISSUE THREAD

**Issue by coool9** [openmultiplayer/launcher#51]
Plz tell. And put it in readme.md or tell it here and link this issue in readme.md

**Comment by AmyrAhmady** [comment]
you create a file, copy english locale file content into it, and start translating
https://github.com/openmultiplayer/launcher/tree/master/src/locales/translations

**Comment by coool9** [comment]
Alright. Also add it in readme.md. 
and what's the deal about src/locales/index.ts? Can a contributor change it or you do it yourself?
