### ISSUE TITLE
The launch page uses a lot of resources and causes hang/freeze

### ISSUE THREAD

**Issue by adib-yg** [openmultiplayer/launcher#67]
I just tried latest [artifact build](https://github.com/openmultiplayer/launcher/actions/runs/7516077627) on my weak PC. 

After I open launcher it shows '_Getting ready to launch..._' page

![Screenshot (290)](https://github.com/openmultiplayer/launcher/assets/92677767/384e8ba8-6f4e-4de2-b25f-89bf7e8fe79c)

After a few seconds, the program freezes (Not Responding)

![Screenshot (287)](https://github.com/openmultiplayer/launcher/assets/92677767/dd97191d-9163-4a85-96b6-5f0e0fe9e150)

Even OS and task manager hangs/freezes and I can't do anything.

![Screenshot (291)](https://github.com/openmultiplayer/launcher/assets/92677767/c1bc805f-0702-4d92-ba7b-6f60be738473)

![Screenshot (295)](https://github.com/openmultiplayer/launcher/assets/92677767/1cf554ea-92fd-463f-989b-c3d989229201)

But it's temporary, it took about 4 minutes to launch the app, after that it's fine

This only happens on weak PCs. 
**I just wanted to report if it is matters, anyway you can close the issue.**

**Comment by AmyrAhmady** [comment]
Please post your system info, like windows version and specs
