### ISSUE TITLE
Score is wrongfully displayed in Launcher "Playerlist"

### ISSUE THREAD

**Issue by Pun1sh3r94** [openmultiplayer/launcher#7]
Launcher shows not the correct amount of Score a Player have

Launcher shows:
![Launcher](https://github.com/openmultiplayer/launcher/assets/59224959/456601b3-b121-4370-9c12-e17cee95f04c)

Ingame shows:
![Ingame](https://github.com/openmultiplayer/launcher/assets/59224959/b260095a-668c-4ff8-806b-fb5cdd76ca0b)

**Comment by adib-yg** [comment]
I reproduced and it's actually wrong.
For example score 100000 shows 34464 in launcher.
**This problem is only with 6-digit scores.**

**Comment by AmyrAhmady** [comment]
Fixed in next version
you can download latest nightly build from here if you don't want to wait for next release.
https://github.com/openmultiplayer/launcher/actions/runs/6833943520
